backend:
  name: git-gateway
  branch: master
  repo: bwalowitz/glanzrock
logo_url: https://d33wubrfki0l68.cloudfront.net/1f4ce04369d08e4f8c3a7ca30a11c4873fda2ae1/3cf4e/static/netlify-cms-logo-5a5d3304b7d2d77ea281363a71dcc970.svg
media_folder: static/img
public_folder: /img

collections:
  - name: "projects"
    label: "Projects"
    folder: "src/projects"
    create: true
    slug: "{{fields.slug}}"
    fields:
      - { label: "Project Title", name: "title", widget: "string" }
      - {
          label: "Project Slug",
          name: "slug",
          widget: "string",
          hint: "The URL of the project, for example: tent-city",
        }
      - { label: "Project Intro", name: "intro", widget: "text" }
      - {
          label: "Project Description",
          name: "description",
          widget: "text",
          required: false,
        }
      - { label: "Project Poster", name: "poster", widget: "image", hint: "Upload JPG sized: 433px wide by 640px tall. Main project thumbnail will be featured in the Home Page Projects section", }
      - label: "Credits"
        name: "credits"
        widget: "list"
        field: { label: Credit, name: credit, widget: string }
      - {
          label: "Project Category",
          name: "category",
          widget: "string",
          required: false,
        }
      - label: "Images"
        name: "images"
        widget: "list"
        hint: "First image needs to be the same thumbnail poster from above. Additional images can be added."
        field: { label: Image, name: image, widget: image }
  - name: "news"
    label: "News"
    folder: "src/news"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "News Article Title", name: "title", widget: "string" }
      - {
          label: "News Article Date",
          name: "date",
          widget: "date",
          format: "MMMM D, YYYY",
        }
      - { label: "News Article Source", name: "source", widget: "string" }
      - { label: "News Article URL", name: "url", widget: "string" }
      - { label: "News Article Image", name: "image", widget: "image" }
